name: Reformat code
on: push

jobs:
  run:
    name: Reformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Format source code
        run: black --exclude /(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|venv)/

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: ${{ GITHUB_ACTOR }}
          author_email: reformat@repo.com
          message: "Reformat codes"
          add: "*.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}